---
title: "BSFRF SBS: Empirical Selectivity"
author: "William T. Stockhausen"
institute: "AFSC/NMFS/NOAA"
date: '`r format(Sys.time(), "%b %e, %Y")`'
fontsize: 11pt 
number-sections: true
number-depth: 3
reference-location: document
reference-section-title: References
bibliography: '`r path.expand("~/Work/Projects/Bibliography/AllRefs.bib")`'
csl: '`r system.file("files/CJFAS.csl",package="wtsQMD")`'
link-citations: true
crossref:
  chapters: false      # prepend label reference numbers by chater number?
  fig-title: Figure    # for caption: default is "Figure")
  tbl-title: Table     # for caption: default is "Table")
  title-delim: "."     # for caption: default is ":")
  fig-prefix: Figure   # for in-text (use [-@fig-ref] to drop prefix in text)
  tbl-prefix: Table    # for in-text (use [-@tbl-ref] to drop prefix in text)
  fig-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  tbl-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  subref-labels: alpha a # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  ref-hyperlink: true    # references are hyperlinked if true
format: 
  html: 
    df-print: paged
    toc: true
    toc-location: right
    fig-width: 8
    fig-asp: 0.4
    fig-dpi: 100
    embed-resources: true
  pdf:
    documentclass: scrartcl
    toc: false
    fig_crop: false
    keep-tex: false
    fig-width: 6.5
    fig-asp: 0.4
    geometry:
      - left=1.0in
      - right=1.0in
      - top=1.0in
      - bottom=1.0in
      - textwidth=6.5in
      - showframe=false
    include-in-header: 
      - text: |
          \usepackage{placeins}
          \extrafloats{500}
          \maxdeadcycles=10000
      - file: !expr 'system.file("files/ltx_ExtraLatexIncludes.tex",package="wtsQMD")'
#      - file: "/Users/williamstockhausen/Work/Programming/R/Library/wtsQMD/files/ltx_ExtraLatexIncludes.tex"
echo: false
warning: false
results: 'hide'
keep-md: true
keep-yaml: false
editor: source
editor_options: 
  chunk_output_type: console
concordance: true
params:
  setup: !expr 'system.file("files/qmd_setup.R",package="wtsQMD")'
  testing: false
  calcESs: false         #--flag to calculate annual ESs (or read in previous results)
  doBS: false            #--flag to do boostrapping analysis (or read in previous results)
  reorderTables: false   #--issue with finding "range" of table values  (don't use)
  reorderFigures: false  #--issue with finding "range" of figure values (don't use)
---
<!-- IMPORTANT: if used as a child doc, all chunk labels must be unique within the overall document -->

<!-- 
  NOTEs: 
     * child_path$peek() gives path to current script.
     * before starting a child document, do 
         "child_path$push(file.path(child_path$peek(),rel_path))" first, 
         where rel_path is the relative path to the child
     * after a child document has finished, do "child_path$pop()" to return to current path value
-->

<!-- if not child doc, set up required objects -->
```{r}
#| label: EmpSel_setup
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: "asis"
  testing = params$testing;
  if (testing) cat(params$setup,"\n\n")
  source(params$setup);
  if (testing) cat("root = ",root,"\n\n")
  reorderTables  = params$reorderTables;
  reorderFigures = params$reorderFigures;
```

```{r}
#| label: setup_EmpSel
#| results: 'asis'
  require(ggplot2);
  require(kableExtra);
  require(tables);
  require(tcsamSurveyData);
  # source(file.path(dirThs,"r_CalcEmpiricalSelectivity.R"));
  # source(file.path(dirThs,"r_ExtractHaulsAndIndivs.R"));
  Sum = wtsUtilities::Sum;
  old_thm = ggplot2::theme_set(cowplot::theme_cowplot(font_size = 10) +
                               cowplot::background_grid() +
                               cowplot::panel_border());
  thm = wtsPlots::getStdTheme();
  options("readr.show_col_types"=FALSE);
  if (testing) cat("dirThs =",child_path$peek(),"\n\n")

  if (rstudioapi::isAvailable()){
    dirThs = file.path(rstudioapi::getActiveProject(),"Analysis/02_Empirical_Selectivity");
  } else if (child_path$peek()!=""){
    dirThs = child_path$peek();
  } else {
    dirThs = ".";
  }
  ##--NOTE: take out or modify the following as necessary
  if (!exists("s")){
    if (rstudioapi::isAvailable())
      fn = file.path(rstudioapi::getActiveProject(),"rda_ProjectSetup.RData");
    if (child_path$peek()!="")
      fn = file.path(child_path$peek(),"../../rda_ProjectSetup.RData");
    #--for debugging: ;
    if (file.exists(fn)) s = wtsUtilities::getObj(fn);
  }
  ##--
```

## Empirical selectivity

### Annual and combined estimates 

```{r EmpSel-GetSBSData}

dfn = file.path(s$dirs$SBS_Data,"rda_Step1_SBS_RawData.RData");#--SBS data list object
lstSBS = wtsUtilities::getObj(dfn);
#--set up processing parameters
aggBySex           =FALSE;
aggByMaturity      =TRUE;
aggByShellCondition=TRUE;
cutpts             =seq(from=25,to=185,by=5);
truncate.low       =TRUE;
truncate.high      =FALSE;
verbosity          =0;

#--determine unique years
uYs<-unique(lstSBS$dfrSD_SBS$YEAR);
```

```{r EmpSel-DefFcn-ExractHaulsAndIndivs}
#--Function to extract haul and individual observations from 
#--(potentially resampled) SBS haul data (see r_ExtractHaulsAndIndivs.R)
extractHaulsAndIndivs<-function(dfrSDr,dfrHD,dfrID,resampleIndivs=FALSE){
  #--order resampled stations by GIS_STATION (could be duplicates)
  qry<- "select * from dfrSDr order by GIS_STATION;";
  dfrSDr<-sqldf::sqldf(qry);
  #--select resampled hauls
  hdvars<-paste0("h.",names(dfrHD),collapse=",");
  qry<-"select
          &&hdvars
        from dfrSDr as s, dfrHD as h
        where s.GIS_STATION=h.GIS_STATION
        order by h.GIS_STATION;"
  qry<-gsub("&&hdvars",hdvars,qry,fixed=TRUE);
  dfrHDr<-sqldf::sqldf(qry);
  #--rename GIS_STATIONs to avoid duplicates
  # stns<-as.character(1:nrow(dfrSDr));
  # dfrSDr$GIS_STATION<-stns;#--can't do this here: must do it outside function
  # dfrHDr$GIS_STATION<-stns;

  #--select resampled indivs
  dfrIDr<-NULL;
  nH<-nrow(dfrHDr);
  cat("Resampling from",nH,"hauls\n");
  for (h in 1:nH){
    dfrIDp<-dfrID[dfrID$HAULJOIN==dfrHDr$HAULJOIN[h],];
    nI<-nrow(dfrIDp);
    if (nI>0){
      idI <- 1:nI;
      if (resampleIndivs) idI <- ceiling(stats::runif(n=nI,min=0,max=nI));#random index to row of dfrIDp
      dfrIDrp<-dfrIDp[idI,];    #extracted individuals
      dfrIDrp$newHAULJOIN<-h;   #append "new" HAULJOIN
      dfrIDr<-rbind(dfrIDr,dfrIDrp);
    }
  }
  dfrHDr$newHAULJOIN<-1:nrow(dfrHDr);#append "new" HAULJOIN
  return(list(dfrSDr=dfrSDr,dfrHDr=dfrHDr,dfrIDr=dfrIDr));
}
```

```{r EmpSel-DefFcn-CalcEmpiricalSelectivity}
#--function to calculate empirical selectivity
calcEmpiricalSelectivity<-function(dfrSD_SBS,
                                    dfrHD_BSFRF_SBS,
                                    dfrID_BSFRF_SBS,
                                    dfrHD_NMFS_SBS,
                                    dfrID_NMFS_SBS,
                                    aggBySex=FALSE,
                                    aggByMaturity=TRUE,
                                    aggByShellCondition=TRUE,
                                    cutpts=seq(from=25,to=185,by=5),
                                    truncate.low=TRUE,
                                    truncate.high=FALSE,
                                    showPlot=FALSE,
                                    verbosity=0){
  #----calculate ZCs for BSFRF SBS data
  lstZCs_BSFRF_SBS<-doCalcs_ZCs(dfrSD_SBS,
                               dfrHD_BSFRF_SBS,
                               dfrID_BSFRF_SBS,
                               calcByEW166=FALSE,
                               aggBySex=aggBySex,
                               aggByMaturity=aggByMaturity,
                               aggByShellCondition=aggByShellCondition,
                               cutpts=cutpts,
                               truncate.low=truncate.low,
                               truncate.high=truncate.high,
                               dropLevels=list(SEX=c("MISSING","HERMAPHRODITIC")),
                               verbosity=verbosity);
  dfrZCs_BSFRF_SBS<-lstZCs_BSFRF_SBS$EBS;
  dfrZCs_BSFRF_SBS$survey<-"BSFRF";

  #----calculate ZCs for NMFS SBS data
  lstZCs_NMFS_SBS<-doCalcs_ZCs(dfrSD_SBS,
                               dfrHD_NMFS_SBS,
                               dfrID_NMFS_SBS,
                               calcByEW166=FALSE,
                               aggBySex=aggBySex,
                               aggByMaturity=aggByMaturity,
                               aggByShellCondition=aggByShellCondition,
                               cutpts=cutpts,
                               truncate.low=truncate.low,
                               truncate.high=truncate.high,
                               dropLevels=list(SEX=c("MISSING","HERMAPHRODITIC")),
                               verbosity=verbosity);
  dfrZCs_NMFS_SBS<-lstZCs_NMFS_SBS$EBS;
  dfrZCs_NMFS_SBS$survey<-"NMFS";

  #----combine size compositions
  dfrZCs<-rbind(dfrZCs_BSFRF_SBS,dfrZCs_NMFS_SBS);
  names(dfrZCs)<-tolower(names(dfrZCs));
  dfrZCs<-dfrZCs[,c("survey","year","sex","maturity","shell_condition","size","numindivs","totabundance")];
  names(dfrZCs)<-c("fleet","y","x","m","s","z","n","val");
  dfrZCs$x<-tolower(dfrZCs$x);
  dfrZCs$m<-tolower(dfrZCs$m);
  dfrZCs$s<-tolower(dfrZCs$s);
  dfrZCs$type<-"observed";

  #--Calculate empirical selectivity as ratio of NMFS to BSFRF size compositions
  dfrZCsp1<-reshape2::dcast(dfrZCs,"type+y+x+z~fleet",fun.aggregate=wtsUtilities::Sum,value.var="n");
  names(dfrZCsp1)[5:6]<-paste0("n_",names(dfrZCsp1)[5:6]);
  dfrZCsp2<-reshape2::dcast(dfrZCs,"type+y+x+z~fleet",fun.aggregate=wtsUtilities::Sum,value.var="val");
  dfrZCsp2[["emp_sel"]]<-dfrZCsp2$NMFS/dfrZCsp2$BSFRF;
  idx<-is.infinite(dfrZCsp2[["emp_sel"]]);
  dfrZCsp2[["emp_sel"]][idx]<-NaN;
  dfrZCsp<-cbind(dfrZCsp1,BSFRF=dfrZCsp2$BSFRF,NMFS=dfrZCsp2$NMFS,emp_sel=dfrZCsp2$emp_sel);

  return(list(dfrESs=dfrZCsp,dfrZCs=dfrZCs));
}
```

```{r EmpSel-DefFcn-PlotEmpiricalSelectivity}
  plotEmpiricalSelectivity<-function(dfrZCs,
                                     dfrESs,
                                     plotPoints=FALSE,
                                     points=list(alpha=0.2,size=0.5,dodge=2.5),
                                     plotLines=FALSE,
                                     plotViolins=TRUE,
                                     violins=list(scale="width",stat="ydensity",dodge=2.5,alpha=0.3),
                                     plotSmooths=TRUE,
                                     smooths=list(method="auto",formula=y~x),
                                     showPlot=FALSE){
    require(ggplot2);
    uXs<-unique(dfrZCs$x);
    plots = list();
    #------estimated total abundance, by size
    for (uX in uXs){
      pByX = list()
      xlim<-c(25,185)
      if (uX=="female") xlim<-c(25,125);
      tmp <- dfrZCs[dfrZCs$x==uX,]
      pl<-wtsPlots::plotMDFR.XY(tmp,
                                 x="z",
                                 value.var="val",
                                 colour="fleet",
                                 fill="fleet",
                                 plotPoints=plotPoints,
                                 points=points,
                                 plotLines=plotLines,
                                 plotViolins=plotViolins,
                                 violins=violins,
                                 agg.formula="type+fleet+y+x+z+iB",
                                 agg.function=wtsUtilities::Sum,
                                 facet_grid=y~x,
                                 scales="free_y",
                                 xlim=xlim,
                                 xlab="size (mm CW)",
                                 ylab="abundance (millions)",
                                 showPlot=FALSE) + wtsPlots::getStdTheme();
      pByX[["ZCs"]] = pl;
      #if (showPlot) print(pl);
      pl <- pl + ggplot2::scale_y_log10();
      pl <- pl + ggplot2::ylab("abundance (millions, log10-scale)");
      pByX[["lnZCs"]] = pl;
      #if (showPlot) print(pl);
      if (plotSmooths) {
        pl <- pl + ggplot2::scale_y_continuous(trans="identity");
        pl <- pl + ggplot2::ylab("abundance (millions)");
        pl <- pl + ggplot2::geom_smooth(alpha=0.3,linetype=2,
                                        method=smooths$method,formula=smooths$formula,
                                        mapping=ggplot2::aes(colour=fleet,fill=fleet));
        pByX[["smZCs"]] = pl;
        #if (showPlot) print(pl);
      }
    }
    #
    #------empirical selectivity, by size
    for (uX in uXs){
      tmp <- dfrESs[dfrESs$x==uX,];
      pl <- wtsPlots::plotMDFR.XY(tmp,
                                   x="z",
                                   value.var="emp_sel",
                                   colour="x",
                                   fill="x",
                                   plotPoints=plotPoints,
                                   points=points,
                                   plotLines=plotLines,
                                   plotViolins=plotViolins,
                                   violins=violins,
                                   facet_grid=y~type+x,
                                   ylim=c(0,1.2),
                                   xlab="size (mm CW)",
                                   ylab="empirical selectivity",
                                   guideTitleColour="sex",
                                   guideTitleFill="sex",
                                   showPlot=FALSE) + wtsPlots::getStdTheme();
      if (plotSmooths) pl <- pl + ggplot2::geom_smooth(alpha=0.3,linetype=2,
                                                       method=smooths$method,formula=smooths$formula,
                                                       colour="blue",fill="blue");
      pByX[["ESs"]] = pl;
      #if (showPlot) print(pl);
      plots[[uX]] = pByX;
    }
    return(plots);
  }
```

```{r EmpSel-CalcESs, cache=TRUE}
if (params$calcESs){
  lstBZCs<-list();
  lstBESs<-list();
  nBs<-0;
  for (iY in uYs){
    #--get actual SBS stations, hauls, and indiv data for year iY
    #--iY = uYs[1];
    dfrYSD_SBS       = lstSBS$dfrSD_SBS       |> dplyr::filter(YEAR==iY);
    dfrYHD_BSFRF_SBS = lstSBS$dfrHD_BSFRF_SBS |> dplyr::filter(YEAR==iY);
    dfrYID_BSFRF_SBS = lstSBS$dfrID_BSFRF_SBS |> dplyr::filter(HAULJOIN %in% dfrYHD_BSFRF_SBS$HAULJOIN);
    dfrYHD_NMFS_SBS  = lstSBS$dfrHD_NMFS_SBS  |> dplyr::filter(YEAR==iY);
    dfrYID_NMFS_SBS  = lstSBS$dfrID_NMFS_SBS  |> dplyr::filter(HAULJOIN %in% dfrYHD_NMFS_SBS$HAULJOIN);
  
    #--get number of stations/hauls in EBS for year iY
    nS_SBS <- nrow(dfrYSD_SBS);
    lstBZCsp<-list();
    lstBESsp<-list();
    for (iB in 0){
      cat("Processing",iB,"of",nBs,"for",iY,"\n");
      #--DON'T resample from SBS stations
      # idS_SBS <- ceiling(stats::runif(n=nS_SBS,min=0,max=nS_SBS));#random index to row of dfrSDy_SBS
      # dfrRSD_SBS<-dfrYSD_SBS[idS_SBS,];#--resampled SBS stations
      dfrRSD_SBS<-dfrYSD_SBS;#--use original SBS stations (will be resampled stations in step3a)
      #----extract BSFRF hauls and individuals (don't really need to do this, but consistent with step3a)
      lst1<-extractHaulsAndIndivs(dfrRSD_SBS,dfrYHD_BSFRF_SBS,dfrYID_BSFRF_SBS,resampleIndivs=FALSE);
      dfrRSD_BSFRF_SBS<-lst1$dfrSDr;#--rows have been reordered in ascending order
      dfrRHD_BSFRF_SBS<-lst1$dfrHDr;#--newHAULJOINs indicate row in dfrRSD_BSFRF_SBS, newHAULJOINS must replace HAULJOINS below
      dfrRID_BSFRF_SBS<-lst1$dfrIDr;#--newHAULJOINs match those in dfrRHD_BSFRF_SBS, newHAULJOINS must replace HAULJOINS below
      rm(lst1);
      #----DON'T resample NMFS hauls and individuals
      lst1<-extractHaulsAndIndivs(dfrRSD_SBS,dfrYHD_NMFS_SBS,dfrYID_NMFS_SBS,resampleIndivs=FALSE);
      dfrRSD_NMFS_SBS<-lst1$dfrSDr;#--rows have been reordered in ascending order
      dfrRHD_NMFS_SBS<-lst1$dfrHDr;#--newHAULJOINs indicate row in dfrRSD_NMFS_SBS, newHAULJOINS must replace HAULJOINS below
      dfrRID_NMFS_SBS<-lst1$dfrIDr;#--newHAULJOINs match those in dfrRHD_NMFS_SBS, newHAULJOINS must replace HAULJOINS below
      rm(lst1);
  
      #--dfrRSD_BSFRF_SBS and dfrRSD_NMFS_SBS are identical
      #--one needs to replace dfrRSD_SBS so re-ordering is correct
      dfrRSD_SBS<-dfrRSD_BSFRF_SBS;
      rm(dfrRSD_BSFRF_SBS,dfrRSD_NMFS_SBS);
  
      #--now replace HAULJOINS with newHAULJOINS
      dfrRHD_BSFRF_SBS$HAULJOIN<-dfrRHD_BSFRF_SBS$newHAULJOIN; dfrRHD_BSFRF_SBS<-wtsUtilities::deleteCol(dfrRHD_BSFRF_SBS,"newHAULJOINS");
      dfrRID_BSFRF_SBS$HAULJOIN<-dfrRID_BSFRF_SBS$newHAULJOIN; dfrRID_BSFRF_SBS<-wtsUtilities::deleteCol(dfrRID_BSFRF_SBS,"newHAULJOINS");
      dfrRHD_NMFS_SBS$HAULJOIN <-dfrRHD_NMFS_SBS$newHAULJOIN;  dfrRHD_NMFS_SBS <-wtsUtilities::deleteCol(dfrRHD_NMFS_SBS, "newHAULJOINS");
      dfrRID_NMFS_SBS$HAULJOIN <-dfrRID_NMFS_SBS$newHAULJOIN;  dfrRID_NMFS_SBS <-wtsUtilities::deleteCol(dfrRID_NMFS_SBS, "newHAULJOINS");
      #--rename GIS_STATIONS to avoid duplicates
      dfrRSD_SBS$GIS_STATION      <-as.character(1:nS_SBS);
      dfrRHD_BSFRF_SBS$GIS_STATION<-as.character(1:nS_SBS);
      dfrRHD_NMFS_SBS$GIS_STATION <-as.character(1:nS_SBS);
  
      #--create single stratum for SBS stations
      dfrRSD_SBS$STRATUM<-"1";
      dfrRSD_SBS$STRATUM_CODE<-"1";
      dfrRSD_SBS$STRATUM_AREA          <-sum(dfrRSD_SBS$STATION_AREA,na.rm=TRUE);
      dfrRSD_SBS$STRATUM_AREA_BYSTATION<-sum(dfrRSD_SBS$STATION_AREA,na.rm=TRUE);
      dfrRHD_BSFRF_SBS$STRATUM<-"1";
      dfrRHD_NMFS_SBS$STRATUM <-"1";
  
      #--calculate empirical selectivity
      lst1<-calcEmpiricalSelectivity(dfrRSD_SBS,
                                     dfrRHD_BSFRF_SBS,
                                     dfrRID_BSFRF_SBS,
                                     dfrRHD_NMFS_SBS,
                                     dfrRID_NMFS_SBS,
                                     aggBySex=aggBySex,
                                     aggByMaturity=aggByMaturity,
                                     aggByShellCondition=aggByShellCondition,
                                     cutpts=cutpts,
                                     truncate.low=truncate.low,
                                     truncate.high=truncate.high,
                                     showPlot=FALSE,
                                     verbosity=0);
      lst1$dfrZCs[["iB"]]<-iB;
      lst1$dfrESs[["iB"]]<-iB;
      lstBZCsp[[as.character(iB)]] = lst1$dfrZCs;
      lstBESsp[[as.character(iB)]] = lst1$dfrESs;
      rm(lst1,dfrRSD_SBS,
         dfrRHD_BSFRF_SBS,dfrRID_BSFRF_SBS,
         dfrRHD_NMFS_SBS,dfrRID_NMFS_SBS);
    }#--iB
    lstBZCs[[as.character(iY)]] = dplyr::bind_rows(lstBZCsp); rm(lstBZCsp);
    lstBESs[[as.character(iY)]] = dplyr::bind_rows(lstBESsp); rm(lstBESsp);
    rm(dfrYSD_SBS,
       dfrYHD_BSFRF_SBS,dfrYID_BSFRF_SBS,
       dfrYHD_NMFS_SBS,dfrYID_NMFS_SBS)
  }#--iY
  dfrZCs = dplyr::bind_rows(lstBZCs); rm(lstBZCs);
  dfrESs = dplyr::bind_rows(lstBESs); rm(lstBESs);
  ofn = file.path(dirThs,"rda_Step1_EmpiricalSelectivityFromData.RData");
  wtsUtilities::saveObj(list(dfrZCs=dfrZCs,dfrESs=dfrESs),fn=ofn);
} else {
  ofn = file.path(dirThs,"rda_Step1_EmpiricalSelectivityFromData.RData");
  lst = wtsUtilities::getObj(ofn);
  dfrZCs = lst$dfrZCs;
  dfrESs = lst$dfrESs;
  rm(lst);
}
```

<!-- ```{r EmpSel-CalcSelPlots-AnnualFs,eval=TRUE} -->
<!-- #--females -->
<!-- dfrZCsp<-dfrZCs[(dfrZCs$x=="female")&(dfrZCs$z<=125),]; -->
<!-- dfrESsp<-dfrESs[(dfrESs$x=="female")&(dfrESs$z<=125),]; -->
<!-- ps = plotEmpiricalSelectivity(dfrZCsp,dfrESsp, -->
<!--                               plotPoints=TRUE, -->
<!--                               points=list(alpha=0.2,size=3,dodge=0), -->
<!--                               plotLines=TRUE, -->
<!--                               plotViolins=FALSE, -->
<!--                               plotSmooths=TRUE, -->
<!--                               smooths=list(method="gam",formula=y~s(x,bs="cs",k=5), -->
<!--                                            knots=c(25,50,75,100,125)), -->
<!--                               showPlot=FALSE)[[1]]; -->
<!-- rm(dfrZCsp,dfrESsp); -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: fig-EmpSel-AnnualZCsF -->
<!-- #| fig-cap: "Annual expanded size compositions for female Tanner crab from SBS data." -->
<!-- #| eval: true -->
<!--   lg = cowplot::get_legend(ps[["ZCs"]]+theme(legend.position="top",legend.margin=margin(0,0,0,0))); -->
<!--   p1 = ps[["ZCs"]]  +theme(legend.position="none",plot.margin=margin(t=0)); -->
<!--   p2 = ps[["lnZCs"]]+theme(legend.position="none",plot.margin=margin(t=0)); -->
<!--   pg1 = cowplot::plot_grid(p1,p2,nrow=1,rel_widths=c(1,1)) -->
<!--   pg2 = cowplot::plot_grid(lg,pg1,ncol=1,rel_heights=c(1,12)) -->
<!--   lstFigs = c(lstFigs,wtsQMD::printGGplot(pg2)); -->
<!--   # if (!isPDF) pg2 else { -->
<!--   #   lbl = getLabel(); -->
<!--   #   cap = "Comparison of annual empirical estimates of survey selectivity."; -->
<!--   #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext))); -->
<!--   #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi); -->
<!--   #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi); -->
<!--   #   rm(lbl,cap,pth); -->
<!--   # } -->
<!--   rm(lg,p1,p2,pg1,pg2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: fig-EmpSel-AnnualEmpSelsF -->
<!-- #| fig-cap: "Empirical estimates of annual survey selectivity for female Tanner crab from SBS data." -->
<!-- #| eval: true -->
<!--   lstFigs = c(lstFigs,wtsQMD::printGGplot(ps[[4]]+theme(legend.position="none"))); -->
<!-- # if (!isPDF) ps[[4]]+theme(legend.position="none") else { -->
<!-- #   lbl = getLabel(); -->
<!-- #   cap = "Comparison of annual empirical estimates of survey selectivity."; -->
<!-- #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext))); -->
<!-- #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi); -->
<!-- #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi); -->
<!-- #   rm(lbl,cap,pth); -->
<!-- # } -->
<!-- rm(ps); -->
<!-- ``` -->

<!-- ```{r EmpSel-CalcSelPlots-AnnualMs,eval=TRUE} -->
<!-- #--males -->
<!-- dfrZCsp<-dfrZCs[(dfrZCs$x=="male")&(dfrZCs$z<=185),]; -->
<!-- dfrESsp<-dfrESs[(dfrESs$x=="male")&(dfrESs$z<=185),]; -->
<!-- ps = plotEmpiricalSelectivity(dfrZCsp,dfrESsp, -->
<!--                               plotPoints=TRUE, -->
<!--                               points=list(alpha=0.2,size=3,dodge=0), -->
<!--                               plotLines=TRUE, -->
<!--                               plotViolins=FALSE, -->
<!--                               plotSmooths=TRUE, -->
<!--                               smooths=list(method="gam",formula=y~s(x,bs="cs",k=7), -->
<!--                                            knots=c(25,50,75,100,125,150,175)))[[1]]; -->
<!-- rm(dfrZCsp,dfrESsp); -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: fig-EmpSel-AnnualZCsM -->
<!-- #| fig-cap: "Annual expanded size compositions for male Tanner crab from SBS data." -->
<!-- #| eval: true -->
<!--   lg = cowplot::get_legend(ps[["ZCs"]]+theme(legend.position="top",legend.margin=margin(0,0,0,0))); -->
<!--   p1 = ps[["ZCs"]]  +theme(legend.position="none",plot.margin=margin(t=0)); -->
<!--   p2 = ps[["lnZCs"]]+theme(legend.position="none",plot.margin=margin(t=0)); -->
<!--   pg1 = cowplot::plot_grid(p1,p2,nrow=1,rel_widths=c(1,1)) -->
<!--   pg2 = cowplot::plot_grid(lg,pg1,ncol=1,rel_heights=c(1,12)) -->
<!--   lstFigs = c(lstFigs,wtsQMD::printGGplot(pg2)); -->
<!--   # if (!isPDF) pg2 else { -->
<!--   #   lbl = getLabel(); -->
<!--   #   cap = "Comparison of annual empirical estimates of survey selectivity."; -->
<!--   #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext))); -->
<!--   #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi); -->
<!--   #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi); -->
<!--   #   rm(lbl,cap,pth); -->
<!--   # } -->
<!--   rm(lg,p1,p2,pg1,pg2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: fig-EmpSel-AnnualEmpSelsM -->
<!-- #| fig-cap: "Empirical estimates of annual survey selectivity for male Tanner crab from SBS data." -->
<!-- #| eval: true -->
<!--   lstFigs = c(lstFigs,wtsQMD::printGGplot(ps[[4]]+theme(legend.position="none"))); -->
<!-- # if (!isPDF) ps[[4]]+theme(legend.position="none") else { -->
<!-- #   lbl = getLabel(); -->
<!-- #   cap = "Comparison of annual empirical estimates of survey selectivity."; -->
<!-- #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext))); -->
<!-- #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi); -->
<!-- #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi); -->
<!-- #   rm(lbl,cap,pth); -->
<!-- # } -->
<!-- rm(ps) -->
<!-- ``` -->

```{r}
#| label: fig-EmpSel-NumbersSampled
#| fig-cap: "Total numbers of crab sampled for the SBS studies."
#--alernative version
  p1 = ggplot(data=dfrZCs,mapping=aes(x=z,y=n,colour=fleet)) +
         geom_line() + geom_point() +
         facet_grid(rows = y~x,scales = "free_y") +
         labs(x="size (mm CW)",y="crab sampled",colour="") + 
         # wtsPlots::getStdTheme() + 
         theme(legend.position="top");
  lstFigs = c(lstFigs,wtsQMD::printGGplot(p1));
  # if (!isPDF) print(p1) else {
  #   lbl = getLabel();
  #   cap = "Comparison of annual empirical estimates of survey selectivity.";
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
```

```{r}
#| label: fig-EmpSel-SizeComps
#| fig-cap: "Annual size compositions derived for the SBS studies."
  p1 = ggplot(data=dfrZCs,mapping=aes(x=z,y=val,colour=fleet)) +
         geom_line() + geom_point() +
         facet_grid(rows = y~x,scales = "free_y") +
         labs(x="size (mm CW)",y="abundance (millions)",colour="") + 
         # wtsPlots::getStdTheme() + 
         theme(legend.position="top")
  lstFigs = c(lstFigs,wtsQMD::printGGplot(p1));
  # if (!isPDF) print(p1) else {
  #   lbl = getLabel();
  #   cap = "Comparison of annual empirical estimates of survey selectivity.";
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
```

```{r}
#| label: fig-EmpSel-Annual
#| fig-cap: "Comparison of annual empirical estimates of survey selectivity."
  tmp = dfrESs;
  tmp$totN = tmp$n_BSFRF+tmp$n_NMFS;
  tmp$y = factor(tmp$y)
  p1 = ggplot(data=tmp,mapping=aes(x=z,y=emp_sel,colour=y,size=totN)) +
         geom_point() + scale_size_area() + 
         geom_line(mapping=aes(x=z,y=emp_sel,colour=y),inherit.aes=FALSE) +
         geom_smooth(mapping=aes(x=z,y=emp_sel),inherit.aes = FALSE) +
         facet_grid(rows = .~x,scales = "free_x") +
         labs(x="size (mm CW)",y="empirical\ncatchability",
              colour="study\nyear",size="crab\nsampled") + 
         # wtsPlots::getStdTheme() + 
         theme(legend.position=c(0.49,0.99),legend.justification=c(1,1));
  lstFigs = c(lstFigs,wtsQMD::printGGplot(p1));
  # if (!isPDF) print(p1) else {
  #   lbl = getLabel();
  #   cap = "Comparison of annual empirical estimates of survey selectivity.";
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=p,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
  rm(tmp,p1);
```

```{r}
#| label: tbl-EmpSelSSs
#| tbl-cap: "Numbers sampled and estimated total abundance."
#| results: "asis"
#--create table of numbers of crab sampled, by year, sex, and gear
require(tables);
tmp  = dfrZCs |> dplyr::group_by(fleet,y,x) |>
                  dplyr::summarize(`number sampled`=wtsUtilities::Sum(n),
                            `total abundance`=wtsUtilities::Sum(val)) |>
                  dplyr::ungroup() |>
                  tidyr::pivot_longer(cols=c("number sampled","total abundance"),names_to="type");
tbl = tables::tabular(Heading("year")*Factor(y,name="year")~
                        Factor(type)*
                        Factor(x,name="sex")*(
                          Heading("group")*Factor(fleet)*value*wtsUtilities::Sum),
                      data=tmp);
colLabels(tbl) = colLabels(tbl)[c(2,4,6),];
if (!isPDF) tables::toHTML(tbl) else {
  lbl = getLabel();
  cap = "Numbers sampled and estimated total abundance.";
  lstTbls[[lbl]] = list(lbl=lbl,cap=cap,tbl=tables::toLatex(tbl));
  rm(lbl,cap,tbl);
}
```

```{r EmpSel-DefModelFcns}
#--fit with smooth models
#----function to do model diagnostics
doDiagnostics<-function(mod){
  summary(mod);
  plot(mod,page=1);
  gam.check(mod);
}

#----function to calculate estimates from model
calcEstimates<-function(mod,zs,yfs){
  dfrPrd<-data.frame(z=rep(zs,length(yfs)),yf=rep(yfs,each=length(zs)));
  prd<-predict(mod,dfrPrd,type="response",se.fit=TRUE);
  cis<-wtsUtilities::calcCIs(prd$fit,sdvs=prd$se.fit,pdfType="lognormal",ci=0.8);
  dfrPrdRes<-cbind(dfrPrd,fit=prd$fit,se=prd$se.fit,lci=cis$lci,uci=cis$uci);
  dfrPrdRes$yf<-factor(dfrPrdRes$yf);
  return(dfrPrdRes);
}

#----function to plot estimates from model
plotEstimates<-function(dfrPrdSel,nm){
  pl<-wtsPlots::plotMDFR.XY(dfrPrdSel,x="z",value.var="fit",colour="yf",facet_grid="yf~.",
                            ylim=c(0,1.2),plotLines=TRUE,plotPoints=FALSE,showPlot=FALSE) + 
        ggplot2::geom_ribbon(mapping=ggplot2::aes(ymin=lci,ymax=uci),alpha=0.4,fill="grey") +
        ggplot2::labs(x="size (mm CW)",y="empirical selectivity") + 
        ggplot2::ggtitle(nm) + 
        wtsPlots::getStdTheme();
  return(pl);
}
```

```{r EmpSel-FitSmoothModels}
#--fit models to "observed" catchability
require(mgcv);
#----list for models
lstMods<-list();
#----fit models by sex
sexes<-c("male","female");
mxZs <-c(180,   120);     #--need one for each sex
nXs<-length(sexes);
for (x_ in 1:nXs){
  sex<-sexes[x_]; mxZ<-mxZs[x_];
  #----emp_avail: gaussian with log link + annual fits
  dfrESsp = dfrESs %>% subset((x==sexes[x_])&(z<=mxZs[x_])) %>%
             dplyr::mutate(yf=factor(y),zf=factor(z),p=NMFS/(NMFS+BSFRF)) %>%
             dplyr::group_by(type,y,x) %>%
             dplyr::mutate(w=(n_BSFRF + n_NMFS)/mean(n_BSFRF + n_NMFS)) %>%
             dplyr::ungroup();
  nm<-paste0(sex,"s: annual fits");
  lstMods[[nm]]<-gam(emp_sel~ yf+s(z,bs="cs",by=yf), weights=w, data=dfrESsp,family=gaussian(link="log"));
  #----emp_avail: gaussian with log link + aggregated fit
  dfrESsp = dfrESs %>% subset((x==sexes[x_])&(z<=mxZs[x_])) %>%
             dplyr::mutate(zf=factor(z),p=NMFS/(NMFS+BSFRF)) %>%
             dplyr::group_by(type,x) %>%
             dplyr::mutate(w=(n_BSFRF + n_NMFS)/mean(n_BSFRF + n_NMFS)) %>%
             dplyr::ungroup();
  nm<-paste0(sex,"s: aggregated fit");
  lstMods[[nm]]<-gam(emp_sel~ s(z,bs="cs"), weights=w, data=dfrESsp,family=gaussian(link="log"));
}
rm(x_,sex,dfrESsp,nm);
```

```{r}
#| label: fig-EmpSelMods
#| fig-cap: 
#|   - !expr 'paste0("Model fits to empirical selectivity for ",sexes[1]," Tanner crab in the SBS studies.")'
#|   - !expr 'paste0("Model fits to empirical selectivity for ",sexes[2]," Tanner crab in the SBS studies.")'
#--plot model estimates of selectivity
yfs<-uYs;
dfrModEsts<-NULL;
for (x_ in 1:nXs){
  sex = sexes[x_];
  zs<-seq(25,mxZs[x_],by=5);
  #--plot annual model
  nm1 <-paste0(sexes[x_],"s: annual fits")
  mdl1 = lstMods[[nm1]];
  tmp<-calcEstimates(mdl1,zs,yfs);
  tmp$model_name<-nm1; 
  plt = plotEstimates(tmp,nm1);
  data=mdl1$model |> dplyr::mutate(w=`(weights)`);
  p1 = plt + ggplot2::geom_point(data=data,mapping=ggplot2::aes(x=z,y=emp_sel,size=w)) +
             ggplot2::geom_hline(yintercept=c(0,0.5,1),linetype=3,colour="grey25") + 
             ggplot2::labs(colour="year",size="relative\nweight",title=NULL);
  tmp$z<-tmp$z+2;#--match z's in assessment
  dfrModEsts<-rbind(dfrModEsts,tmp);
  
  #--plot aggregated model
  nm2  = paste0(sexes[x_],"s: aggregated fit")
  mdl2 = lstMods[[nm2]];
  tmp  = calcEstimates(mdl2,zs," ");
  tmp$model_name<-nm2;
  plt = plotEstimates(tmp,nm2);
  data=mdl2$model |> dplyr::mutate(w=`(weights)`,yf=" ");
  p2 = plt + ggplot2::geom_point(data=data,mapping=ggplot2::aes(x=z,y=emp_sel,size=w)) +
             ggplot2::geom_hline(yintercept=c(0,0.5,1),linetype=3,colour="grey25") + 
             ggplot2::labs(colour="empirical",size="relative\nweight",title = NULL);
  tmp$z<-tmp$z+2;#--match z's in assessment
  dfrModEsts<-rbind(dfrModEsts,tmp);
  
  #--combine plots
  pg = ggpubr::ggarrange(p1,p2,ncol=1,heights=c(4,2));
  if (!isPDF) print(pg) else {
    lbl = getLabel(x_);
    cap = paste0("Model fits to empirical selectivity for ",sexes[x_]," Tanner crab in the SBS studies.");
    pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
    lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
    ggsave(pth,plot=pg,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
    rm(lbl,cap,pth);
  }
  #--ggplot2::ggsave(paste0("EstimatedEmpiricalSelectivityFromData.",sex,"s.pdf"),pg,width=6.5,height=8);
  modDiags = cbind(model=c(nm1,nm2),AIC(mdl1,mdl2),BIC(mdl1,mdl2)[,2],
                   "% deviance explained"=100*c(1-mdl1$deviance/mdl1$null.deviance,
                                                1-mdl2$deviance/mdl2$null.deviance));
  #--readr::write_csv(modDiags,file = paste0("ModelDiagnostics.",sex,".csv"));
  rm(sex,zs,nm1,mdl1,tmp,plt,nm2,mdl2,pg)
}
wtsUtilities::saveObj(dfrModEsts,"rda_Step2_EmpSel_dfrModEsts.RData");
```


### Bootstrapping analysis

```{r EmpSel-DoBootstrapping, cache=TRUE}
if (params$doBS){
  #--do bootstrapping
  lstBZCs<-list();
  lstBESs<-list();
  nBs<-1000;
  for (iY in uYs){
    #--get actual SBS stations, hauls, and indiv data for year iY
    dfrYSD_SBS      <-lstSBS$dfrSD_SBS       |> dplyr::filter(YEAR==iY);
    dfrYHD_BSFRF_SBS<-lstSBS$dfrHD_BSFRF_SBS |> dplyr::filter(YEAR==iY);
    dfrYID_BSFRF_SBS<-lstSBS$dfrID_BSFRF_SBS |> dplyr::filter(HAULJOIN %in% dfrYHD_BSFRF_SBS$HAULJOIN);
    dfrYHD_NMFS_SBS <-lstSBS$dfrHD_NMFS_SBS  |> dplyr::filter(YEAR==iY);
    dfrYID_NMFS_SBS <-lstSBS$dfrID_NMFS_SBS  |> dplyr::filter(HAULJOIN %in% dfrYHD_NMFS_SBS$HAULJOIN);
  
    #--get number of stations/hauls in EBS for year iY
    nS_SBS <- nrow(dfrYSD_SBS);
    lstBpZCs = list();
    lstBpESs = list();
    for (iB in 1:nBs){
      cat("Processing",iB,"of",nBs,"for",iY,"\n");
      #--resample from SBS stations
      idS_SBS <- ceiling(stats::runif(n=nS_SBS,min=0,max=nS_SBS));#random index to row of dfrSDy_SBS
      dfrRSD_SBS<-dfrYSD_SBS[idS_SBS,];#--resampled SBS stations
  
      #----resample BSFRF hauls and individuals
      lst1<-extractHaulsAndIndivs(dfrRSD_SBS,dfrYHD_BSFRF_SBS,dfrYID_BSFRF_SBS,resampleIndivs=TRUE);
      dfrRSD_BSFRF_SBS<-lst1$dfrSDr;#--rows have been reordered in ascending order
      dfrRHD_BSFRF_SBS<-lst1$dfrHDr;#--newHAULJOINs indicate row in dfrRSD_BSFRF_SBS, newHAULJOINS must replace HAULJOINS below
      dfrRID_BSFRF_SBS<-lst1$dfrIDr;#--newHAULJOINs match those in dfrRHD_BSFRF_SBS, newHAULJOINS must replace HAULJOINS below
      rm(lst1);
      #----resample NMFS hauls and individuals
      lst1<-extractHaulsAndIndivs(dfrRSD_SBS,dfrYHD_NMFS_SBS,dfrYID_NMFS_SBS,resampleIndivs=TRUE);
      dfrRSD_NMFS_SBS<-lst1$dfrSDr;#--rows have been reordered in ascending order
      dfrRHD_NMFS_SBS<-lst1$dfrHDr;#--newHAULJOINs indicate row in dfrRSD_NMFS_SBS, newHAULJOINS must replace HAULJOINS below
      dfrRID_NMFS_SBS<-lst1$dfrIDr;#--newHAULJOINs match those in dfrRHD_NMFS_SBS, newHAULJOINS must replace HAULJOINS below
      rm(lst1);
  
      #--dfrRSD_BSFRF_SBS and dfrRSD_NMFS_SBS are identical
      #--one needs to replace dfrRSD_SBS so re-ordering is correct
      dfrRSD_SBS<-dfrRSD_BSFRF_SBS;
      rm(dfrRSD_BSFRF_SBS,dfrRSD_NMFS_SBS);
  
      #--now replace HAULJOINS with newHAULJOINS
      dfrRHD_BSFRF_SBS$HAULJOIN<-dfrRHD_BSFRF_SBS$newHAULJOIN; dfrRHD_BSFRF_SBS<-wtsUtilities::deleteCol(dfrRHD_BSFRF_SBS,"newHAULJOINS");
      dfrRID_BSFRF_SBS$HAULJOIN<-dfrRID_BSFRF_SBS$newHAULJOIN; dfrRID_BSFRF_SBS<-wtsUtilities::deleteCol(dfrRID_BSFRF_SBS,"newHAULJOINS");
      dfrRHD_NMFS_SBS$HAULJOIN <-dfrRHD_NMFS_SBS$newHAULJOIN;  dfrRHD_NMFS_SBS <-wtsUtilities::deleteCol(dfrRHD_NMFS_SBS, "newHAULJOINS");
      dfrRID_NMFS_SBS$HAULJOIN <-dfrRID_NMFS_SBS$newHAULJOIN;  dfrRID_NMFS_SBS <-wtsUtilities::deleteCol(dfrRID_NMFS_SBS, "newHAULJOINS");
      #--rename GIS_STATIONS to avoid duplicates
      dfrRSD_SBS$GIS_STATION      <-as.character(1:nS_SBS);
      dfrRHD_BSFRF_SBS$GIS_STATION<-as.character(1:nS_SBS);
      dfrRHD_NMFS_SBS$GIS_STATION <-as.character(1:nS_SBS);
  
      #--create single stratum for SBS stations
      dfrRSD_SBS$STRATUM<-"1";
      dfrRSD_SBS$STRATUM_CODE<-"1";
      dfrRSD_SBS$STRATUM_AREA          <-sum(dfrRSD_SBS$STATION_AREA,na.rm=TRUE);
      dfrRSD_SBS$STRATUM_AREA_BYSTATION<-sum(dfrRSD_SBS$STATION_AREA,na.rm=TRUE);
      dfrRHD_BSFRF_SBS$STRATUM<-"1";
      dfrRHD_NMFS_SBS$STRATUM <-"1";
  
      #--calculate empirical selectivity
      lst1<-calcEmpiricalSelectivity(dfrRSD_SBS,
                                    dfrRHD_BSFRF_SBS,
                                    dfrRID_BSFRF_SBS,
                                    dfrRHD_NMFS_SBS,
                                    dfrRID_NMFS_SBS,
                                    aggBySex=aggBySex,
                                    aggByMaturity=aggByMaturity,
                                    aggByShellCondition=aggByShellCondition,
                                    cutpts=cutpts,
                                    truncate.low=truncate.low,
                                    truncate.high=truncate.high,
                                    showPlot=FALSE,
                                    verbosity=0);
      lst1$dfrZCs[["iB"]]<-iB;
      lst1$dfrESs[["iB"]]<-iB;
      lstBpZCs[[as.character(iB)]] = lst1$dfrZCs;
      lstBpESs[[as.character(iB)]] = lst1$dfrESs;
      rm(lst1,dfrRSD_SBS,
         dfrRHD_BSFRF_SBS,dfrRID_BSFRF_SBS,
         dfrRHD_NMFS_SBS,dfrRID_NMFS_SBS);
    }#--iB
    lstBZCs[[as.character(iY)]] = dplyr::bind_rows(lstBpZCs); rm(lstBpZCs);
    lstBESs[[as.character(iY)]] = dplyr::bind_rows(lstBpESs); rm(lstBpESs);
    rm(dfrYSD_SBS,
       dfrYHD_BSFRF_SBS,dfrYID_BSFRF_SBS,
       dfrYHD_NMFS_SBS,dfrYID_NMFS_SBS);
  }#--iY
  dfrBZCs = dplyr::bind_rows(lstBZCs); rm(lstBZCs);
  dfrBESs = dplyr::bind_rows(lstBESs); rm(lstBESs);
  save(dfrBZCs,dfrBESs,
       file=file.path(dirThs,"rda_Step3_EmpiricalSelectivityFromBootstrapping.RData"));
} else {
  load(file.path(dirThs,"rda_Step3_EmpiricalSelectivityFromBootstrapping.RData"));
}
```

```{r EmpSel-DefFcn-PlotEmpSel}
plotEmpSel<-function(dfr,colour,z_lim=c(22.5,187.5),n_min=0,wrap=TRUE){
  p = ggplot(dfr |> dplyr::filter(n_BSFRF+n_NMFS >= n_min),
             aes(x=z,y=emp_sel,colour={{colour}},fill={{colour}},group=paste(y,iB)));
  p = p + geom_line(alpha=0.1,size=0.1) + 
          geom_point(alpha=0.1,size=0.1,position=position_jitter(0.5)) + 
          geom_line(data=dfr |> dplyr::filter(iB==1),alpha=1,linewidth=1);
  if (wrap){
    p = p + geom_smooth(mapping=aes(group=NULL),colour=NA,fill="yellow",alpha=1,
                        method="gam",formula=y~s(x,bs="cs",k=5));
  } else {
    p = p + geom_smooth(mapping=aes(x=z,y=emp_sel),colour=NA,fill="yellow",alpha=1,inherit.aes=FALSE,
                        method="gam",formula=y~s(x,bs="cs",k=5));
  }
  p = p + geom_hline(yintercept=c(0,1),linetype=2) + 
          geom_hline(yintercept=c(0.5),linetype=3) + 
          labs(x="size (mm CW)",y="empirical selectivity",colour="year",fill="year") + 
          scale_y_continuous(limits=c(0,3),oob=scales::squish) + 
          scale_x_continuous(limits=z_lim,oob=scales::squish) + 
          scale_colour_discrete(aesthetics=c("colour","fill")) + 
          guides(colour=guide_legend(override.aes=list(alpha=1))) + 
          wtsPlots::getStdTheme() + 
          theme(panel.grid.major=element_line(colour="gray75"),
                panel.grid.minor=element_line(colour="white"));
  if (wrap) p = p + facet_wrap(~y,nrow=2);
  return(p);
}
```

```{r}
#| label: fig-EmpSel-PlotBESsF
#| fig-cap: "Boostrapped empirical selectivities for female Tanner crab in the SBS studies. Upper plot: Annual SBS-derived selectivities (heavy line is mean value, yellow curve is smoothed fit); lower plot: all SBS years combined, yellow curve is smoothed fit to all."
  #--females
  dfrESsp<-dfrBESs |> dplyr::filter((x=="female"),dplyr::between(z,25,125));
  p1 = plotEmpSel(dfrESsp,colour=factor(y),z_lim=c(22.5,127.5),n_min=0,wrap=TRUE) + 
         theme(legend.position="none",axis.title.x=element_blank());
  p2 = plotEmpSel(dfrESsp,colour=factor(y),z_lim=c(22.5,127.5),n_min=0,wrap=FALSE) +
         theme(legend.position=c(0.01,0.99),legend.justification=c(0,1));
  pg = cowplot::plot_grid(p1,p2,ncol=1);
  lstFigs = c(lstFigs,wtsQMD::printGGplot(pg));
  # if (!isPDF) print(pg) else {
  #   lbl = getLabel();
  #   cap = paste0("Boostrapped empirical selectivities for female Tanner crab in the SBS studies. ",
  #                "Upper plot: Annual SBS-derived selectivities (heavy line is mean value, yellow curve is smoothed fit); ",
  #                "lower plot: all SBS years combined, yellow curve is smoothed fit to all.");
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=pg,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
  rm(dfrESsp,p1,p2,pg);
```

```{r}
#| label: fig-EmpSel-PlotBESsM
#| fig-cap: "Boostrapped empirical selectivities for male Tanner crab in the SBS studies. Upper plot: Annual SBS-derived selectivities (heavy line is mean value, yellow is smoothed fit); lower plot: all SBS years combined, yellow is smoothed fit to all."
  #--males
  dfrESsp<-dfrBESs |> dplyr::filter((x=="male"),dplyr::between(z,25,185));
  p1 = plotEmpSel(dfrESsp,colour=factor(y),z_lim=c(22.5,187.5),n_min=0,wrap=TRUE) + 
         theme(legend.position="none",axis.title.x=element_blank());
  p2 = plotEmpSel(dfrESsp,colour=factor(y),z_lim=c(22.5,187.5),n_min=0,wrap=FALSE) +
         theme(legend.position=c(0.01,0.99),legend.justification=c(0,1));
  pg = cowplot::plot_grid(p1,p2,ncol=1);
  lstFigs = c(lstFigs,wtsQMD::printGGplot(pg));
  # if (!isPDF) print(pg) else {
  #   lbl = getLabel();
  #   cap = paste0("Boostrapped empirical selectivities for male Tanner crab in the SBS studies. ",
  #                "Upper plot: Annual SBS-derived selectivities (heavy line is mean value, yellow is smoothed fit); ",
  #                "lower plot: all SBS years combined, yellow is smoothed fit to all.");
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=pg,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
  rm(dfrESsp,p1,p2,pg);
```

```{r EmpSel-CaclStats}
#--calculate bootstrap means by sex, year, size
dfrMeans<-reshape2::dcast(dfrBESs,"x+y+z~.",fun.aggregate=mean,na.rm=TRUE,value.var="emp_sel");
names(dfrMeans)[4]<-"mean";
dfrStds <-reshape2::dcast(dfrBESs,"x+y+z~.",fun.aggregate=var, na.rm=TRUE,value.var="emp_sel");
dfrStds[["."]]<-sqrt(dfrStds[["."]]);
names(dfrStds)[4]<-"stddev";
cis<-wtsUtilities::calcCIs(dfrMeans$mean,sdvs=dfrStds$stddev,pdfType="normal",ci=0.8);
dfrStats<-cbind(dfrMeans,stddev=dfrStds[["stddev"]],lci=cis$lci,uci=cis$uci);
dfrStats$y<-factor(dfrStats$y)
```

```{r}
#| label: fig-EmpSel-BStats-MnCIs
#| fig-cap: "Mean and 80% confidence intervals for annual empirical selectivity from bootstrapping analysis. Upper plot: females; lower plot: males. Results for different SBS study years are shown with different colors."
  pl<-wtsPlots::plotMDFR.XY(dfrStats,x="z",value.var="mean",
                            plotLines=TRUE,plotPoints=FALSE,colour="y",facet_grid="x~.",showPlot=FALSE)
  pl<-pl + ggplot2::geom_ribbon(mapping=aes(ymin=lci,ymax=uci,fill=y),alpha=0.4,colour=NA);
  pl<-pl + ggplot2::labs(x="size (mm CW)",y="empirical selectivity",colour="year",fill="year");
  pl<-pl + ggplot2::geom_hline(yintercept=c(0,1),linetype=2,colour="grey50");
  pl<-pl + ggplot2::scale_y_continuous(limits=c(-0.5,2),oob=scales::squish);
  pl<-pl+wtsPlots::getStdTheme();
  lstFigs = c(lstFigs,wtsQMD::printGGplot(pl));
  # if (!isPDF) print(pl) else {
  #   lbl = getLabel();
  #   cap = paste0("Mean and 80% confidence intervals for annual empirical selectivity from bootstrapping analysis. Upper plot: females; lower plot: males. Results for different SBS study years are shown with different colors.");
  #   pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
  #   lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
  #   ggsave(pth,plot=pg,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
  #   rm(lbl,cap,pth);
  # }
```

```{r EmpSel-DefFcn-PlotMdlPred}
  #--define function for plotting model responses
  plotPred<-function(nm,mod,zs,yfs,zfs){
    dfrPrd = tidyr::crossing(z=zs,yf=yfs,zf=zfs);
    prd<-predict(mod,dfrPrd,type="response",se.fit=TRUE);
    cis<-wtsUtilities::calcCIs(prd$fit,sdvs=prd$se.fit,pdfType="lognormal",ci=0.8);
    dfrPrdRes<-cbind(dfrPrd,fit=prd$fit,se=prd$se.fit,lci=cis$lci,uci=cis$uci);
    pl<-wtsPlots::plotMDFR.XY(dfrPrdRes,x="z",value.var="fit",colour="yf",
                              plotLines=TRUE,plotPoints=FALSE,showPlot=FALSE)
    pl<-pl + ggplot2::geom_ribbon(mapping=aes(x=z,ymin=lci,ymax=uci,fill=yf),alpha=0.4,colour=NA,inherit.aes=FALSE);
    pl<-pl + ggplot2::labs(x="size (mm CW)",y="empirical selectivity",fill="year",colour="year");
    pl<-pl + ggplot2::ggtitle(nm); 
    pl<-pl + ggplot2::geom_hline(yintercept=c(0,1),linetype=2);
    pl<-pl + wtsPlots::getStdTheme() + ggplot2::theme(panel.grid=ggplot2::element_line(colour="grey"));
    return(pl)
  }
```

```{r EmpSel-BStats-FitModels,cache=TRUE}
#--run models to fit smooth curves to bootstrapping results
if (FALSE){
  #----list for all models
  lstMods<-list();
  for (x_ in c("male","female")){
    #--list for models of sex x_
    lstModsX<-list();
    #--extract relevant bootstrap results
    dfrESsX = dfrBESs |> 
                dplyr::filter(x==x_) |> 
                dplyr::mutate(yf = factor(y),
                              zf = factor(z),
                              nTot = n_BSFRF+n_NMFS);
    #----gaussian with log link, by year
    nm<-paste0(x_,"s: gaussian(log link): emp_sel ~ s(z,bs='tp',id=1) + s(z,bs='re',by=yf,id=1)");
    lstModsX[[nm]]<-gam(emp_sel ~ s(z,bs="tp",id=1) + s(z,bs="re",by=yf,id=1),
                       data=dfrESsX,family=gaussian(link="log"),weights=nTot);
    #----gaussian with log link
    nm<-paste0(x_,"s: gaussian(log link) emp_sel~ s(z,bs='tp') + s(zf,yf,bs='re')");
    lstModsX[[nm]]<-gam(emp_sel~ s(z,bs="tp") + s(zf,yf,bs="re"), 
                       data=dfrESsX,family=gaussian(link="log"),weights=nTot);
    #--add to results list-by-sex
    lstMods[[x_]] = lstModsX;
  }#--x_
  save(dfrStats,lstMods,file=file.path(dirThs,"rda_Step4_EmpiricalSelectivtyFromBootstrapping.stats.RData"));
} else  
  load(file=file.path(dirThs,"rda_Step4_EmpiricalSelectivtyFromBootstrapping.stats.RData"));
```

```{r, dependson="EmpSel-BStats-FitModels",results="asis"}
#| label: EmpSel-BStats-Models
#| fig-asp: 1.4
  #--print results for the models
  zs<-list(male  =seq(27,182,by=5),
           female=seq(27,127,by=5));
  for (x_ in c("male","female")){
    cat("\n\n");
    cat("--------------------------------------------------------------\n");
    cat("--------------------------------------------------------------\n");
    cat("results for",x_,"\n")
    #--extract model results
    lstModsX = lstMods[[x_]];
    #--extract relevant bootstrap results
    dfrESsX = dfrBESs |> 
                dplyr::filter(x==x_) |> 
                dplyr::mutate(yf = factor(y),
                              zf = factor(z),
                              nTot = n_BSFRF+n_NMFS);
    for (nm in names(lstModsX)){
      cat("\n--------------------------------------------------------------\n");
      cat("Results for",nm,"\n")
      summary(lstModsX[[nm]]);
      #plot(lstModsX[[nm]],page=1);
      gam.check(lstModsX[[nm]]);
    }
    print(anova(lstModsX[[1]],lstModsX[[2]]));
    print(AIC(lstModsX[[1]],lstModsX[[2]]));
  }
```

```{r, dependson="EmpSel-BStats-FitModels"}
#| label: EmpSel-BStats-PlotModels
#| fig-cap: 
#| - "Model fits and 80% confidence intervals for annual empirical selectivity from the bootstrapping analysis for male Tanner crab. Plot titles give model definitions." 
#| - "Model fits and 80% confidence intervals for annual empirical selectivity from the bootstrapping analysis for female Tanner crab. Plot titles give model definitions."
#--plot results for the models
zs<-list(male  =seq(27,182,by=5),
         female=seq(27,127,by=5));
for (x_ in c("male","female")){
  cat("\n\n");
  cat("--------------------------------------------------------------\n");
  cat("--------------------------------------------------------------\n");
  cat("results for",x_,"\n")
  #--extract model results
  lstModsX = lstMods[[x_]];
  #--extract relevant bootstrap results
  dfrESsX = dfrBESs |> 
              dplyr::filter(x==x_) |> 
              dplyr::mutate(yf = factor(y),
                            zf = factor(z),
                            nTot = n_BSFRF+n_NMFS);
  for (nm in names(lstModsX)){
    # cat("\n--------------------------------------------------------------\n");
    # cat("results for",nm,"\n")
    # summary(lstModsX[[nm]]);
    if (testing) plot(lstModsX[[nm]],page=1);
    #gam.check(lstModsX[[nm]]);
  }
  # print(anova(lstModsX[[1]],lstModsX[[2]]));
  # print(AIC(lstModsX[[1]],lstModsX[[2]]));
  nm<-names(lstModsX)[1];
  p1 = plotPred(nm,lstModsX[[nm]],zs=zs[[x_]],yfs=dfrESsX$yf,zfs=dfrESsX$zf);
  p1 = p1 + scale_y_continuous(limits=c(0,3),oob=scales::squish)
  print(p1);
  nm<-names(lstModsX)[2];
  p2 = plotPred(nm,lstModsX[[nm]],zs=zs[[x_]],yfs=0,zfs=0);
  print(p2);
  pg = cowplot::plot_grid(p1,p2,ncol=1);
  if (!isPDF) print(pg) else {
    lbl = getLabel();
    cap = paste0("Model fits and 80% confidence intervals for annual empirical selectivity ",
                 "from the bootstrapping analysis for ",x_," Tanner crab. ",
                 "Plot titles give model definitions.");
    pth = file.path(dirFigs,basename(xfun::with_ext(knitr::fig_path(),def_ext)));
    lstFigs[[lbl]] = list(lbl=lbl,cap=cap,pth=pth,wid=def_wid,dpi=def_dpi);
    ggsave(pth,plot=pg,width=def_wid,height=def_wid/def_asp,units="in",dpi=def_dpi);
    rm(lbl,cap,pth);
  }
  rm(p1,p2,lstModsX,dfrESsX)
}
```

<!-- references -->
```{r,eval=!knitr::opts_knit$get("child")&(!isPDF),results='asis'}
  cat("# References {-}\n");
  cat("::: {#refs}\n");
  cat(":::\n\n");
```

<!-- tables, if not child doc and lstTbls is not empty -->
```{r}
#| label: tables_EmpSel
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printTablesSectionFromList.R",package="wtsQMD"));
```

<!-- figures, if not child doc and lstFigs is not empty -->
```{r}
#| label: figures_EmpSel
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printFiguresSectionFromList.R",package="wtsQMD"));
```
