---
title: "SBS Studies: Results"
author:
- name: William T. Stockhausen
  affiliations:
    - id: afsc-refm
      name: "Alaska Fisheries Science Center"
      department: "Resource Ecology and Fisheries Management"
      address: 
        - "7600 Sand Point Way N.E."
        - "Seattle, Washington 98115-6349"
date: '`r format(Sys.time(), "%b %e, %Y")`'
fontsize: 11pt 
number-sections: true
number-depth: 3
reference-location: document
reference-section-title: References
bibliography: '`r path.expand("~/Work/Projects/Bibliography/AllRefs.bib")`'
csl: '`r system.file("files/CJFAS.csl",package="wtsQMD")`'
link-citations: true
crossref:
  chapters: false      # prepend label reference numbers by chater number?
  fig-title: Figure    # for caption: default is "Figure")
  tbl-title: Table     # for caption: default is "Table")
  title-delim: "."     # for caption: default is ":")
  fig-prefix: Figure   # for in-text (use [-@fig-ref] to drop prefix in text)
  tbl-prefix: Table    # for in-text (use [-@tbl-ref] to drop prefix in text)
  fig-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  tbl-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  subref-labels: alpha a # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  ref-hyperlink: true    # references are hyperlinked if true
format: 
  html: 
    df-print: paged
    toc: true
    toc-location: right
    fig-width: 8
    fig-asp: 0.6
    fig-dpi: 100
    embed-resources: true
    include-in-header: 
      - '`r system.file("files/in-line_math_mode.html",package="wtsQMD")`'
  pdf:
    documentclass: scrartcl
    toc: false
    fig_crop: false
    keep-tex: false
    fig-width: 6.5
    fig-asp: 0.6
    geometry:
      - left=1.0in
      - right=1.0in
      - top=1.0in
      - bottom=1.0in
      - textwidth=6.5in
      - showframe=false
    include-in-header: 
      - text: |
          \usepackage{placeins}
          \extrafloats{500}
          \maxdeadcycles=10000
      - file: '`r system.file("files/ltx_ExtraLatexIncludes.tex",package="wtsQMD")`'
echo: false
warning: false
results: 'hide'
keep-md: false
keep-yaml: false
editor: source
editor_options: 
  chunk_output_type: console
concordance: true
params:
  setup: !expr 'system.file("files/qmd_setup.R",package="wtsQMD")'
  testing: false
  calcESs: false         #--flag to calculate annual ESs (or read in previous results)
  doBS: false            #--flag to do boostrapping analysis (or read in previous results)
  reorderTables: false   #--issue with finding "range" of table values  (don't use)
  reorderFigures: false  #--issue with finding "range" of figure values (don't use)
---
<!-- IMPORTANT: if used as a child doc, all chunk labels must be unique within the overall document -->

<!-- 
  NOTEs: 
     * child_path$peek() gives path to current script.
     * before starting a child document, do 
         "child_path$push(file.path(child_path$peek(),rel_path))" first, 
         where rel_path is the relative path to the child
     * after a child document has finished, do "child_path$pop()" to return to current path value
-->

<!-- if not child doc, set up required objects -->
```{r}
#| label: Results_setup
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: "asis"
  testing = params$testing;
  if (testing) cat(params$setup,"\n\n")
  #--the following script sets: 
  #----1. root is knitr::opts_knit$get("root.dir") or ""
  #----2. child_path$peek() is:
  #------a. previously set by parent document, otherwise
  #------b. if rstudioapi::isAvailable()==TRUE, set to path to active RStudio document
  #---------(dirname(rstudioapi::getActiveDocumentContext()$path)), otherwise
  #------c. "." (i.e., current working directory if rstudioapi::isAvailable()==FALSE)
  source(params$setup);
  #--check settings
  if (testing) cat("root = '",root,"'\n",sep="")
  if (testing) cat("child_path$peek() = '",child_path$peek(),"'\n\n",sep="")
  reorderTables  = params$reorderTables;
  reorderFigures = params$reorderFigures;
```

```{r}
#| label: setup_Results
#| results: 'asis'
#| warning: !expr testing
  require(ggplot2);
  require(kableExtra);
  require(tables);
  Sum = wtsUtilities::Sum;
  old_thm = ggplot2::theme_set(cowplot::theme_cowplot(font_size = 10) +
                               cowplot::background_grid() +
                               cowplot::panel_border());
  thm = wtsPlots::getStdTheme();
  options("readr.show_col_types"=FALSE);
  if (testing) warning("dirThs =",child_path$peek(),"\n\n")

  if (child_path$peek()!=""){ #--running
    dirThs = child_path$peek();
  # } else if (rstudioapi::isAvailable()){    #--running directly in RStudio
  #   dirThs = file.path(rstudioapi::getActiveProject(),"TM_SBS");
  } else {
    dirThs = ".";
  }
  ##--NOTE: take out or modify the following as necessary
  ###--rda_ProjectSetup.RData should be located in the main directory for the project
  if ((exists("prj_setup"))&&(class(prj_setup)=="list")){
    warning("list 'prj_setup' exists from parent document.")
  } else {
    warning("'prj_setup' does not exist, so will try to open 'rda_ProjectSetup.RData'.")
    if (child_path$peek()!=""){
      fn = file.path(child_path$peek(),"../rda_ProjectSetup.RData");
      warning("setting fn from child_path$peek()");
    } else {
      warning("could not use child_path$peek to set fn");
      if (rstudioapi::isAvailable()){
        #--fall back to looking in project folder
        fn = file.path(rstudioapi::getActiveProject(),"rda_ProjectSetup.RData");
        warning("Setting fn using Active Project path");
      } else {
        warning("rstudioapi not available");
        #--fall back to current working directory
        fn = "rda_ProjectSetup.RData";
      }
    }
    #--for debugging: ;
    if (file.exists(fn)) {
      prj_setup = wtsUtilities::getObj(fn);
    } else  {stop(paste0("fn '",fn,"' does not exist!"));}
  }
```

# Results {#sec-Results}

<!-- ## SBS surveys results {#sec-Results-SBS-Surveys} -->
```{r Results-SBS-Surveys, child=file.path(prj_setup$dirs$SBS_Data,"q02_SBS_DataResults.qmd"),eval=TRUE}
```


## Survey-level selectivity {#sec-Results-SurvSel}
```{r Results-SurvSel, child=file.path(prj_setup$dirs$EmpSel,"q02_EmpSelResults.qmd"),eval=TRUE}
```


<!-- ## Sediment characteristics {#sec-Results-SedChars} -->
```{r Results-SedChars, child=file.path(prj_setup$dirs$SedAnls,"q02_SedimentResults.qmd"),eval=TRUE}
```


## Haul-level selectivity {#sec-Results-HaulSel}


<!-- references -->
```{r refs_Results,eval=!knitr::opts_knit$get("child")&!isPDF,results='asis'}
  cat("# References {-}\n");
  cat("::: {#refs}\n");
  cat(":::\n\n");
```

<!-- tables, if not child doc and lstTbls is not empty -->
```{r}
#| label: tables_Results
#| eval: !expr '(!knitr::opts_knit$get("child"))&&isPDF'
#| results: asis
  wtsUtilities::saveObj(lstTbls,"rda_lstTbls.RData");
  source(system.file("files/printTablesSectionFromList.R",package="wtsQMD"));
```

<!-- figures, if not child doc and lstFigs is not empty -->
```{r}
#| label: figures_Results
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printFiguresSectionFromList.R",package="wtsQMD"));
```
