#--plot results
source("plotEmpiricalSelectivity.R")
load(file="EmpiricalSelectivityFromBootstrapping.RData");
pdf("EmpiricalSelectivityFromBootstrapping.pdf",width=8,height=6);
#--females
dfrZCsp<-dfrZCs[(dfrZCs$x=="female")&(dfrZCs$z<=125),];
dfrESsp<-dfrESs[(dfrESs$x=="female")&(dfrESs$z<=125),];
plotEmpiricalSelectivity(dfrZCsp,dfrESsp,
                          plotPoints=FALSE,
                          points=list(alpha=0.2,size=0.5,dodge=2.5),
                          plotLines=FALSE,
                          plotViolins=TRUE,
                          plotSmooths=TRUE,
                          smooths=list(method="gam",formula=y~s(x,bs="cs",k=5),knots=c(25,50,75,100,125)));
#--males
dfrZCsp<-dfrZCs[(dfrZCs$x=="male")&(dfrZCs$z<=185),];
dfrESsp<-dfrESs[(dfrESs$x=="male")&(dfrESs$z<=185),];
plotEmpiricalSelectivity(dfrZCsp,dfrESsp,
                          plotPoints=FALSE,
                          points=list(alpha=0.2,size=0.2,dodge=2.5),
                          plotLines=FALSE,
                          plotViolins=TRUE,
                          plotSmooths=TRUE,
                          smooths=list(method="gam",formula=y~s(x,bs="cs",k=7),knots=c(25,50,75,100,125,150,175)));
dev.off();
